#Пример 1.2.1

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3, 1])
print(x[1, :])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


#Пример 1.2.2

In [ ]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d, '\n')


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19] 



#Пример 1.2.3

In [ ]:
import numpy as np
z = np.random.random((10, 10))
zmin, zmax, zmean = z.min(), z.max(), z.mean()
print(zmin, zmax, zmean)

0.0017569188558391735 0.9949005674029334 0.5317277001722701


#Пример 1.2.4

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#Пример 1.2.5

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#Пример 1.2.6

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


#Задание 1.3.1

In [ ]:
arr = np.zeros((8, 8))

arr[::2, 1::2] = 1
arr[1::2,::2 ] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#Задание 1.3.2

In [ ]:
arr = np.array([np.arange(5)]*5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#Задание 1.3.3

In [ ]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.58957309 0.1829903  0.27940653]
  [0.06144076 0.65541849 0.8811614 ]
  [0.98742655 0.03752236 0.63743725]]

 [[0.16986367 0.11839827 0.87571317]
  [0.44162085 0.40878028 0.09396723]
  [0.26443353 0.644783   0.20700267]]

 [[0.72706155 0.9878845  0.39778539]
  [0.81375824 0.30231502 0.4754606 ]
  [0.08421828 0.3136061  0.20226955]]]


#Задание 1.3.4

In [ ]:
a = np.ones((6,6))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#Задание 1.3.5

In [ ]:
arr = np.random.random(6)
arr = np.sort(arr)[::-1]
print(f'Reversed sort: {arr}')

Reversed sort: [0.86917498 0.76476872 0.65853745 0.44975495 0.35605661 0.34888363]


#Задание 1.3.6

In [ ]:
arr = np.random.random((2,2))
print(f'Форма: {np.shape(arr)}')
print(f'Размер: {np.size(arr)}')
print(f'Разменость: {np.ndim(arr)}')

Форма: (2, 2)
Размер: 4
Разменость: 2


#Пример 2.2.1

In [ ]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1, s2, s3, sep='\n')

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


#Пример 2.2.2

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


#Пример 2.2.3

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

#Пример 2.2.4

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

#Пример 2.2.5

In [ ]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

#Пример 2.2.6

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

#Пример 2.2.7

In [ ]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

#Задание 2.3.1

In [ ]:
x = pd.Series([4, 13], ['a1', 'b1'])
y = pd.Series([6, 20], ['a2', 'b2'])
range = np.sqrt(((y['a2'] - x['a1']) ** 2 + (y['b2'] - x['b1']) ** 2))
print(f'Евклидово расстояние = {range}')

Евклидово расстояние = 7.280109889280518


#Задание 2.3.2

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
df = pd.read_csv(url, on_bad_lines='skip')
df.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

#Задание 2.3.3

In [ ]:
print(f'Size - {df.shape}')
print(df.describe())
df[df['age'] == 90].iloc[5:11]

Size - (45222, 12)
                age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000


age         workclass  education_num      marital_status  \
3734   90           Private              7       Never-married   
4681   90           Private             10       Never-married   
4835   90           Private              5       Never-married   
4921   90         Local-gov             14  Married-civ-spouse   
4953   90           Private             14       Never-married   
5730   90  Self-emp-not-inc             13  Married-civ-spouse   

             occupation   relationship   race  gender  hours_per_week  \
3734  Handlers-cleaners      Own-child  White    Male              40   
4681      Other-service  Not-in-family  Other    Male              35   
4835       Adm-clerical  Not-in-family  White  Female              40   
4921    Exec-managerial        Husband  White    Male              60   
4953    Exec-managerial  Not-in-family  Other    Male              50   
5730     Prof-specialty        Husband  White    Male              50   

     native_country  capital income_status  
3734  United-States        0         <=50K  
4681  United-States        0         <=50K  
4835  United-States        0         <=50K  
4921  United-States    20051          >50K  
4953  United-States        0          >50K  
5730  United-States    10566         <=50K

#Пример 3.2.1

In [ ]:
import numpy as np
from sklearn import preprocessing

#Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
#Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
#Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

#Пример 3.2.2

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
#Создать шкалировщик
scaler = preprocessing.StandardScaler()
#Преобразовать признак
standardized = scaler.fit_transform(x)
#Показать признак
print(standardized)

print('Среднее:', round(standardized.mean()))
print('Стандартное отклонение:', standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


#Пример 3.2.3

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21],
                       'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

#Задание 3.3.2

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)
#Вычисляем среднее и стандартное отклонение по колонке 'sepal_width_cm'
sepal_width_cm_mean = df['sepal_width_cm'].mean()
sepal_width_cm_std = df['sepal_width_cm'].std()

#Минимаксное преобразование по колонке 'sepal_length_cm'
#Создаем шкалировщик
minmax_scaler = MinMaxScaler()
#Прошкалируем признак
df[['sepal_length_cm']] = minmax_scaler.fit_transform(df[['sepal_length_cm']])

#Z-масштабирование по колонке 'sepal_width_cm'
#Создаем шкалировщик 
scaler = preprocessing.StandardScaler()
#Прошкалируем признак
df[['sepal_width_cm']] = scaler.fit_transform(df[['sepal_width_cm']])

#Вывод результатов
print(df.head())
print('Среднее:', round(sepal_width_cm_mean, 4))
print('Стандартное отклонение:', round(sepal_width_cm_std, 4))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
Среднее: 3.054
Стандартное отклонение: 0.4336
