# Пример 1.1.1
Рассмотрим программу обучения персептрона на языке Python. Сначала
рассмотрим основной класс персептрона, который умеет учиться по
тестовым данным.


In [ ]:
# класс, который реализует персептрон и его обучение
class Perceptron:
    def __init__(self, N):
        # создать нулевые веса
        self.w = list()
        for i in range(N):
            self.w.append( 0)
    # метод для вычисления значения персептрона
    def calc(self, x):
        res = 0
        for i in range(len(self.w)):
            res = res + self.w[i] * x[i]
        return res
    # пороговая функция активации персептрона
    def sign(self, x):
        if self.calc(x) > 0:
            return 1
        else:
            return -1
    # обучение на одном примере
    def learn(self, la, x, y):
        # обучаем только, когда результат неверный
        if y * self.calc(x) <= 0:
            for i in range(len(self.w)):
                self.w[i] = self.w[i] + la * y * x[i]
    # обучение по всем данным Т - кортеж примеров
    def learning(self, la, T):
        # цикл обучения
        for n in range(100):
            # обучение по всем набору примеров
            for t in T:
                self.learn(la, t[ 0], t[1])

In [ ]:
# создаем класс двумерного персептрона
perceptron = Perceptron(2)
la = 0.1 # константа обучения
# создаем примеры
T = list()
T.append([[2,1], 1])
T.append([[3,2], 1])
T.append([[4,1], 1])
T.append([[1,2], -1])
T.append([[2,3], -1])
T.append([[5,7], -1])
perceptron.learning(la, T) # обучение пeрсептрона
print(perceptron.w) # печатаем веса
# проверим работу на тестовых примерах
print(perceptron.sign([1.5, 2]))
print(perceptron.sign([3, 1.5]))
print(perceptron.sign([5,1]))
print(perceptron.sign([5,10]))

[0.1, -0.1]
-1
1
1
-1


# Пример 1.1.2
Для написания кода нейрона будем использовать библиотеку Pytnon
— NumPy:


In [ ]:
import numpy as np 
def sigmoid(x):
    # Функция активации: f(x) = 1 / (1 + e^(-х)) 
    return 1 / (1 + np.exp(-x))
class Neuron:
    def __init__(self, weights, bias):
        self. weights = weights 
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias 
        return sigmoid(total)

weights = np.array([0, 1]) # w1 = 0, w2 = 1 
bias = 4                   # c = 4 
n = Neuron(weights, bias) 
x = np.array([2, 3])       # x = 2, y = 3 
print(n. feedforward(x))   # 0.9990889488055994

0.9990889488055994


In [ ]:
import numpy as np 
class OurNeuralNetwork:
    '''
    Данные нейросети:
        - два входа 
        - два нейрона в скрытых слоях (h1, h2) 
        - выход (o1)
    Нейроны имеют идентичные веса и пороги:
        - w = [0, 1]
        - b = 0
    '''
    def __init__(self):
        weights = np.array([0, 1]) 
        bias = 0 
        # Класс Neuron из предыдущего раздела 
        self.h1 = Neuron(weights, bias) 
        self.h2 = Neuron(weights, bias) 
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x) 
        out_h2 = self.h2.feedforward(x) 
        # Входы для o1 - это выходы h1 u h2 
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2])) 
        return out_o1

network = OurNeuralNetwork() 
x = np.array([2, 3]) 
print(network.feedforward(x)) # 0.7216325609518421

0.7216325609518421


# Задание
Реализовать классы нейросетей по аналогии с классом OurNeuralNetwork. 
Данные нейросети:
 три входа (𝑥1, 𝑥2, 𝑥3);
 три нейрона в скрытых слоях (ℎ1, ℎ2, ℎ3);
 выход (𝑜1).
Нейроны имеют идентичные веса и пороги:
 𝑤 = [0.5, 0.5, 0.5]
 𝑏 = 0
Данные нейросети:
 два входа (𝑥1, 𝑥2);
 два нейрона в скрытых слоях (ℎ1, ℎ2);
 два выхода (𝑜1, 𝑜2
).
Нейроны имеют идентичные веса и пороги:
 𝑤 = [1, 0];
 𝑏 = 1.
Реализуйте классы нейронных сетей с использованием других функций 
активации.

In [ ]:
import numpy as np
def Sigmoid(x):
    return 1 / (1 + np.exp(-x))
def Tanh(x):
    return np.tan(x)
def ReLU(x):
    return max(0,x)

class Neuron:
    def __init__(self, w, b):
        self.w = w
        self.b = b
    def ffSigmoid(self, inputs):
        total = np.dot(self.w, inputs) + self.b
        return sigmoid(total)
    def ffTanh(self, inputs):
        total = np.dot(self.w, inputs) + self.b
        return Tanh(total)
    def ffReLU(self, inputs):
        total = np.dot(self.w, inputs) + self.b
        return ReLU(total)

class NeuralNetwork1:
    def __init__(self):
        w = np.array([0.5, 0.5, 0.5])
        b = 0
        self.h1 = Neuron(w, b)
        self.h2 = Neuron(w, b)
        self.h3 = Neuron(w, b)
        self.o1 = Neuron(w, b)
    def feedforwardSigmoid(self, x):
        out1 = self.h1.ffSigmoid(x)
        out2 = self.h2.ffSigmoid(x)
        out3 = self.h3.ffSigmoid(x)
        outf = self.o1.ffSigmoid(np.array([out1, out2, out3]))
        return outf
    def feedforwardTanh(self, x):
        out1 = self.h1.ffTanh(x)
        out2 = self.h2.ffTanh(x)
        out3 = self.h3.ffTanh(x)
        outf = self.o1.ffTanh(np.array([out1, out2, out3]))
        return outf
    def feedforwardReLU(self, x):
        out1 = self.h1.ffReLU(x)
        out2 = self.h2.ffReLU(x)
        out3 = self.h3.ffReLU(x)
        outf = self.o1.ffReLU(np.array([out1, out2, out3]))
        return outf
    
class NeuralNetwork2:
    def __init__(self):
        w = np.array([1, 0])
        b = 1
        self.h1 = Neuron(w, b)
        self.h2 = Neuron(w, b)
        self.o1 = Neuron(w, b)
        self.o2 = Neuron(w, b)
    def feedforwardSigmoid(self, x):
        out1 = self.h1.ffSigmoid(x)
        out2 = self.h2.ffSigmoid(x)
        out1 = self.o1.ffSigmoid(np.array([out1, out2]))
        out2 = self.o2.ffSigmoid(np.array([out1, out2]))
        return out1, out2
    def feedforwardTanh(self, x):
        out1 = self.h1.ffTanh(x)
        out2 = self.h2.ffTanh(x)
        out1 = self.o1.ffTanh(np.array([out1, out2]))
        out2 = self.o2.ffTanh(np.array([out1, out2]))
        return out1, out2
    def feedforwardReLU(self, x):
        out1 = self.h1.ffReLU(x)
        out2 = self.h2.ffReLU(x)
        out1 = self.o1.ffReLU(np.array([out1, out2]))
        out2 = self.o2.ffReLU(np.array([out1, out2]))
        return out1, out2
    
network1 = NeuralNetwork1()
x1 = np.array([1, 2, 3])
print('Первая нейросеть')
print('Sigmoid: ', network1.feedforwardSigmoid(x1))
print('Tanh: ', network1.feedforwardTanh(x1))
print('ReLU: ', network1.feedforwardReLU(x1))
print()
network2 = NeuralNetwork2()
x2 = np.array([2, 3])
print('Вторая нейросеть')
print('Sigmoid: ', network2.feedforwardSigmoid(x2))
print('Tanh: ', network2.feedforwardTanh(x2))
print('ReLU: ', network2.feedforwardReLU(x2))

Первая нейросеть
Sigmoid:  0.8067238139969796
Tanh:  -0.21713906537767277
ReLU:  4.5

Вторая нейросеть
Sigmoid:  (0.8757270529783324, 0.8671195555587996)
Tanh:  (1.1555911185916798, -1.5104758308623794)
ReLU:  (4, 5)


# Задание

Используйте классы MLPClassified и MLPRegressor для классификации и 
регрессии произвольных данных из интернета. Проведите анализ 
атрибуты, полученных моделей.
Для классификации можете взять набор данных Ирисов:
https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
а для регрессии датасет зависимости заработной платы от опыта работы:
https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv 

In [ ]:
from sklearn.datasets import load_iris, load_digits
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.model_selection import train_test_split

print('----------MLPClassifier----------\n')
data = load_digits()
X_data, Y_data = data.data, data.target
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, train_size=.80, test_size=.20, stratify=Y_data, random_state=123)
mlp_classifier = MLPClassifier(random_state=123)
mlp_classifier.fit(X_train, Y_train)
Y_preds = mlp_classifier.predict(X_test)

print(Y_preds[:20])
print(Y_test[:20])
print('Dataset Sizes:', X_data.shape, Y_data.shape)
print('Train/Test Sizes:', X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)
print('Test Accuracy: %.3f'%mlp_classifier.score(X_test, Y_test))
print('Training Accuracy: %.3f'%mlp_classifier.score(X_train, Y_train))
print('Loss:', mlp_classifier.loss_)
print('Number of Coefs:', len(mlp_classifier.coefs_))
print('Number of Intercepts:', len(mlp_classifier.intercepts_))
print('Number of Iterations for Which Estimator Ran:', mlp_classifier.n_iter_)
print('Name of Output Layer Activation Function:', mlp_classifier.out_activation_)

print('\n----------MLPRegressor----------\n')
data = load_digits()
X_data, Y_data = data.data, data.target
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, train_size=.80, test_size=.20, stratify=Y_data, random_state=123)
mlp_regressor = MLPRegressor(random_state=123)
mlp_regressor.fit(X_train, Y_train)
Y_preds = mlp_regressor.predict(X_test)

print(Y_preds[:20])
print(Y_test[:20])
print('Dataset Sizes:', X_data.shape, Y_data.shape)
print('Train/Test Sizes:', X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)
print('Test R^2 Score: %.3f'%mlp_regressor.score(X_test, Y_test))
print('Training R^2 Score: %.3f'%mlp_regressor.score(X_train, Y_train))
print('Loss:', mlp_regressor.loss_)
print('Number of Coefs:', len(mlp_regressor.coefs_))
print('Number of Iterations for Which Estimator Ran:', mlp_regressor.n_iter_)
print('Name of Output Layer Activation Function:', mlp_regressor.out_activation_)

----------MLPClassifier----------

[5 9 9 6 1 6 6 9 8 7 4 2 1 4 3 1 4 7 0 1]
[5 9 9 6 1 6 6 9 8 7 4 2 1 4 3 1 4 7 0 1]
Dataset Sizes: (1797, 64) (1797,)
Train/Test Sizes: (1437, 64) (360, 64) (1437,) (360,)
Test Accuracy: 0.983
Training Accuracy: 1.000
Loss: 0.0034728684994180608
Number of Coefs: 2
Number of Intercepts: 2
Number of Iterations for Which Estimator Ran: 125
Name of Output Layer Activation Function: softmax

----------MLPRegressor----------

[ 5.35172001  8.03061748 11.42724672  5.98585707  1.85649195  5.31132098
  5.46991711  9.77748793  8.10760734  7.82960361  3.82243672  2.36692296
  0.62682947  4.50317838  3.74246433 -0.11246477  3.81734324  6.59523704
 -0.24429108  0.36959613]
[5 9 9 6 1 6 6 9 8 7 4 2 1 4 3 1 4 7 0 1]
Dataset Sizes: (1797, 64) (1797,)
Train/Test Sizes: (1437, 64) (360, 64) (1437,) (360,)
Test R^2 Score: 0.878
Training R^2 Score: 0.983
Loss: 0.07309221240680908
Number of Coefs: 2
Number of Iterations for Which Estimator Ran: 200
Name of Output Layer Ac

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
